twig:
    file_name_pattern: '*.twig'
    form_theme: 'form/custom_form.html.twig'
    globals:
        society_info: '@App\Service\SocietyService'
        campagne_info: '@App\Service\CampagneService'

when@test:
    twig:
        strict_variables: true
