version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${POSTGRES_VERSION:-10.8.3}
    environment:
      MARIADB_DATABASE: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    volumes:
      - paie_db:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  paie_db:
###< doctrine/doctrine-bundle ###
