services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    networks:
      - orbis_paie
    environment:
      PMA_HOST: database
  ###> doctrine/doctrine-bundle ###
  database:
    networks:
      - orbis_paie
    image: mysql:8.0.35
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-main}
      MYSQL_USER: ${MYSQL_USER:-offset}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
    ports:
      - '3307:3306'
    volumes:
      - paie_db:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  paie_db:
###< doctrine/doctrine-bundle ###
networks:
  orbis_paie:
    driver: bridge
